### ISSUE TITLE
Sub category display

### ISSUE THREAD

**Issue by LetMeDecay** [pichalite/nodebb-theme-material#42]
upgrade NodeBB 1.0.3 to 1.1.0
v1.0.3 sub category is a block, v1.1.0 is item

This is Vanilla

![Imgur](http://i.imgur.com/20ACGUd.png)

This is Material

![Imgur](http://i.imgur.com/4e26Amw.png)

**Comment by pichalite** [comment]
Just because vanilla theme displays subcategories as cards doesn't mean every other theme has to display them the same way. Every theme can display items on pages they way it wants.

Anyway, material theme has a settings page in the admin control panel where you have an option to display the subcategories as cards.
